### ISSUE TITLE
[Error] Binary XML file line #31: You must supply a layout_height attribute on Huawei Mate 7

### ISSUE THREAD

**Issue by szywind** [szywind/cs407-android-lab3-ORMlab#2]
02-26 14:56:44.220 3131-3131/? W/View: requestLayout() improperly called by com.android.systemui.statusbar.phone.IconMerger{43293bc0 V.E..... ......I. 0,0-162,75 #7f0a0068 app:id/notificationIcons} during layout: running second layout pass
02-26 14:56:44.240 2945-2961/? W/ResourceType: Attempt to retrieve bag 0x7f090030 which is invalid or in a cycle.
02-26 14:56:44.240 3468-3468/? I/HwLauncher: Launcher onPause()
02-26 14:56:44.240 3407-3407/? I/K3V3CpuGovernorPolicy: set scene Hmp policy : 300 , 150
02-26 14:56:44.245 2945-2961/? W/WindowManager: Token{440fbbf8 ActivityRecord{43235008 u0 com.cs407_android.ormlab/.MainActivity t140}} failed creating starting window
                                                java.lang.RuntimeException: Binary XML file line #31: You must supply a layout_height attribute.
                                                    at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:533)
                                                    at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:5969)
                                                    at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6137)
                                                    at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:1857)
                                                    at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1769)
                                                    at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:58)
                                                    at android.view.LayoutInflater.rInflate(LayoutInflater.java:777)
                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:512)
                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:409)
                                                    at android.view.LayoutInflater.inflate(LayoutInflater.java:358)
                                                    at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3081)
                                                    at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3144)
                                                    at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1727)
                                                    at com.android.internal.policy.impl.PhoneWindowManager.addStartingWindow(PhoneWindowManager.java:1909)
                                                    at huawei.com.android.internal.policy.impl.HwPhoneWindowManager.addStartingWindow(HwPhoneWindowManager.java:187)
                                                    at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:7415)
                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                    at android.os.Looper.loop(Looper.java:136)
                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
02-26 14:56:44.245 3468-3468/? W/HwLauncher: Launcher.MotionManager failed to stop TYPE_SHAKE_START_PRIVACY
02-26 14:56:44.295 2945-3043/? I/PowerManagerService: canDreamLocked:mCharingBase=false
02-26 14:56:44.295 2945-3043/? I/PowerManagerService: canDreamLocked:mChargingMode=0
02-26 14:56:44.315 3468-3468/? I/HwLauncher: Launcher onStop()

**Comment by szywind** [comment]
[Solution] 
modified android:theme="@style/AppTheme" in AndroidManifest.xml to android:theme="@style/Theme.AppCompat.Light"

[References] 
https://github.com/singwhatiwanna/dynamic-load-apk/issues/35
https://github.com/singwhatiwanna/dynamic-load-apk/issues/31
http://stackoverflow.com/questions/14529590/what-causes-runtimeexception-binary-xml-file-line-20-you-must-supply-a-layou
